version: '3.7'
services:
  database:
    image: "postgres:latest"
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-developer}
        - POSTGRES_USER=${POSTGRES_USER:-developer}
        - POSTGRES_DB=${POSTGRES_DB:-django_q_view}
        - PGDATA=${PGDATA:-/var/lib/postgresql/data/pgdata}
    privileged: true
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
    restart: on-failure
    volumes:
      - redis:/data
  django:
    image: django-q-view:dev
    command: /bin/bash
    stdin_open: true
    tty: true
    depends_on:
      - database
      - redis
    working_dir: /django/django_q_view/
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      - REDIS_HOST=redis
      - SHELL=/bin/bash
      - DATABASE_URL=postgres://developer:developer@database:5432/django_q_view
      - LOG_LEVEL=DEBUG
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - .:/django/django_q_view/
      - ~/.git-hooks:/django/.git-hooks:ro
      - ~/.gitconfig:/django/.gitconfig:ro
      - ~/.ssh:/django/.ssh:ro
volumes:
  db:
  redis:
